openapi: 3.1.0
info:
  title: goshelf
  description: |-
    This is the REST API definition for goshelf, a demo I (Max Clark) created for my Canonical assessment. Thanks for viewing!
  contact:
    email: clark.max.a@gmail.com
  license:
    name: MIT
  version: 1.0.0
servers:
  - url: http://0.0.0.0/api/v1